#!/usr/bin/env bash
# This script transfers a file from client machine to server.
# It only accepts 4 arguments

if [ "$#" -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file="$1"
ip="$2"
user="$3"
ssh_key="$4"

sudo scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file" "$user@$ip":~
