#!/usr/bin/env bash
# This script configures a new ubuntu machine

#update the server and install nginx
apt-get -y update
apt-get install -y nginx

#start nginx

echo "Hello World!" | tee /var/www/html/index.html

service nginx start
