#!/usr/bin/env bash
# This script configures a new ubuntu machine

#update the server and install nginx
sudo apt-get update
sudo apt-get install -y nginx

#start nginx
sudo service nginx start

sudo echo "Hello World!" | tee /var/www/html/index.html

sudo service nginx reload
