#!/usr/bin/env bash
# This script configures a new ubuntu machine

#update the server and install nginx
apt-get -y update
apt-get install -y nginx

echo "Hello World!" | tee /var/www/html/index.html

# Redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4
sudo sed -i '/server_name _;/a \ \ \ \ \ \ \ \ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH3-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Start nginx
service nginx start
