#!/usr/bin/env bash
# This script configures a new ubuntu machine

#update the server and install nginx
apt-get -y update
apt-get install -y nginx

echo "Hello World!" | tee /var/www/html/index.html

# Redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4
sudo sed -i '/^server {/a \
    location \/redirect_me {\
        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

# Start nginx
service nginx start
