#!/usr/bin/env bash
# This script configures a new ubuntu machine

# Add custom http response header
sed -i '/error_page.*/a \ \ \ \ \ \ \ \ add_header X-Served-By "465573-web-02";' /etc/nginx/sites-available/default

# Reload the server
service nginx reload
