#!/usr/bin/env bash
# Configure new machine
# shellcheck disable=SC2154

# Update and install nginx
apt-get -y update
apt-get -y install nginx

# Changes the root page to contain the stril 'Hello World!'
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Add configuration for the redirect_me
sudo sed -i '53i\location =  /redirect_me { return 301 http://youtube.com;}' /etc/nginx/sites-enabled/default

# Add 404 error page
printf "Ceci n'est pas une page\n" > /usr/share/nginx/html/404.html
sudo sed -i '53i\       error_page 404 /404.html;\n             location = /404.html {\n                      root /usr/share/nginx/html;\n                   internal;}' /etc/nginx/sites-enabled/default

# Add custom http response header
sudo sed -i "29i\       add_header X-Served-By \$HOSTNAME;" /etc/nginx/nginx.conf
sudo sed -i "51i\       add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-enabled/default

# Restart the nginx service
if [ "$(pgrep nginx)" ]; then
        service nginx restart
else
        service nginx start
fi
