#!/usr/bin/env bash
# This script configures a new ubuntu machine

# Read servername
server_name=$(hostname)

# Add custom http response header
sed -i "/error_page.*/a \ \ \ \ \ \ \ \ add_header X-Served-By \"$server_name\";" /etc/nginx/sites-available/default

# Restart nginx
service nginx reload
