#!/usr/bin/env bash
# This script installs and configures HAproxy on your lb-01 server.

# Update and install haproxy
apt-get -y update
apt-get install -y haproxy

# Create configuration
configuration="
frontend main
        bind *:80
	default_backend web_servers
	
backend web_servers
	balance roundrobin
	server 465573-web-01 100.25.222.12:80 check
	server 465573-web-02 54.210.122.255:80 check
"
echo "$configuration" | tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
