#!/usr/bin/env bash
#This script tells story about /etc/password

IFS=$'\n'
while read -r line
do
	user=$(echo "$line" | cut -d ":" -f 1)
	gang=$(echo "$line" | cut -d ":" -f 3)
	lives=$(echo "$line" | cut -d ":" -f 6)
	rides=$(echo "$line" | cut -d ":" -f 7)
	place=$(echo "$line" | cut -d ":" -f 4)
	pass=$(echo "$line" | cut -d ":" -f 2)
	info=$(echo "$line" | cut -d ":" -f 5)

	echo "The user $user is part of the $gang gang, lives in $lives and rides $rides. $place's place is protected by the passcode $pass, more info about the user here: $info"
done < "/etc/passwd"
