#!/usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01

apt update
apt install ufw

# Allow for ports 22, 443 and 80
ufw allow 22
ufw allow 443
ufw allow 80

# Enable ufw
ufw enable
